sudo: required

language: generic

services: 
  - docker

before_install:
  - docker build -t reactdemoapp -f Dockerfile.dev . 
  
# script:
#   - docker run reactdemoapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "docker-travis-bucket"
  bucket_path: "docker-react"
  
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  
  on:
    branch: main

