sudo: required

language: generic

services: 
  - docker

before_install:
  - docker build -t reactdemoapp -f Dockerfile.dev . 
  
script:
  - docker run -e CI=true reactdemoapp npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "docker-travis-bucket"
  bucket_path: "docker-react"
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  on:
    branch: main

