FROM node:12-alpine as Builder

WORKDIR "./app"

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=Builder /app/build /usr/share/nginx/html